# Generated by Django 5.0.6 on 2024-07-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='dni',
            field=models.CharField(max_length=100, verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='telefono'),
        ),
    ]
