# Generated by Django 5.0.6 on 2024-07-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_worker_dni_alter_worker_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='dni',
            field=models.CharField(max_length=100, unique=True, verbose_name='dni'),
        ),
    ]
